### ISSUE TITLE
Update K3s demo docs

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse-kubernetes#211]
- Since K3s 3.x, no more provisioning of local path provisioner necessary.
- Syntax changed.
- No longer at IQSS org

Edit to pull from Github, see #210 

kustomization.yaml:
```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../demo

resources:
  - ingress.yaml

images:
  - name: iqss/dataverse-k8s
    newName: ghcr.io/gdcc/dataverse-k8s
    newTag: "4.20"
  - name: iqss/solr-k8s
    newName: ghcr.io/gdcc/solr-k8s

patches:
  - patch-pvc-k3s.yaml
```
