### ISSUE TITLE
log4j vulnerability

### ISSUE THREAD

**Issue by dtandersen** [IQSS/dataverse-kubernetes#225]
iqss/solr-k8s is vulnerable to CVE-2021-44228.

https://logging.apache.org/log4j/2.x/security.html

**Comment by poikilotherm** [comment]
Thx for the hint.
I suggest people use a patch like this (it's what we did):
```
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: solr
spec:
  template:
    spec:
      containers:
        - name: solr
          env:
            # Mitigate Log4Shell / CVE-2021-44228
            - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
              value: "true"
```

and add it to their `kustomization.yaml`:
```
patchesStrategicMerge:
  - patch-env.yaml
```
