### ISSUE TITLE
Add ingress example

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse-kubernetes#97]
Copied from #95 by @cledevedec:
> I also had to add an `ingress` like I was using **traefik** as a reverse proxy for my cluster.

We should provide an example deployment for traefik in case someone needs it.

**Comment by cledevedec** [comment]
Here is how you can use traefik for your ingress  
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
  labels:
    environment: <your-env>
    k8s-app: dataverse
    trigram: k8s
  name: dataverse
  namespace: dataverse-test
spec:
  tls:
  - hosts:
    - <@host>
    secretName: dataverse-certs
  rules:
  - host: <@host>
    http:
      paths:
      - backend:
          serviceName: dataverse
          servicePort: 8080
        path: /
status:
  loadBalancer: {}
```
